### PR TITLE
Update BI operation classes. Fixes #77

### LINKED ISSUE #77: Update Operation classes for BI
Some operation classes need to be amended.

* [x] queries 14 and 16 have a `todo` string in their CSV headers for tests.
* [x] query 2: params are out of sync, the driver specifies countries (a collection) instead of two countries, `country1` and `country`. The driver also has `endDate` and `messageThreshold`, which the documentation does not specify. Also, the driver specifies `dateA`/`dateB`, instead of `date1`/`date2`.
* [x] query 3: params are out of sync, the driver defines a range, the docs specify `year` and `month`
* [x] query 5: remove unused field `popularForumLimit`
* [x] query 10: `date` param is missing
* [x] query 12: `likeCount` should be renamed to `likeThreshold`
* [x] query 16: param 2 should be `country` (not `tag`), param 3 should be `tagClass` (not `country`)
* [x] query 18: param 1 should be `creationDate` in the docs, not `date` --> change the docs and rev. Q12, see https://github.com/ldbc/ldbc_snb_docs/issues/70
* [x] query 22: `countryX` and `countryY` should be called `country1` and `country2` (also check interactive/complex/3)

### PR DESCRIPTION
**Pull request by szarnyasg**
Commits for issue #77.

### CODE REVIEW

**Comment by szarnyasg** [comment]
@alexaverbuch can we merge this?

**Comment by ArnauPrat** [comment]
It would be great if we could merge this in order to update the Sparksee implementation

**Comment by ArnauPrat** [comment]
I've adapted the Sparksee Driver to this pull request. I've also reviewed the changes and so far they look good.

**Comment by ArnauPrat** [comment]
@szarnyasg  I am not sure about the change in query2, where you removed the endOfSimulation. Currently, the data generator cannot guarantee that there is not going to be any event past 2013-01-01. Imposing such a hard constrain could have negative effects over the distributions. Basically, having a sharp threshold (e.g. everything that is simulated after the simulation time is not serialized) would make not to produce exactly the desired distributions. I any case, we guarantee that no persons are created after 2013-01-01, so this would not affect this query.

**Comment by szarnyasg** [comment]
https://github.com/ldbc/ldbc_snb_docs/blob/master/query-specifications/bi-read-02.yaml#L17

**Comment by szarnyasg** [comment]
This was actually introduced in https://github.com/ldbc/ldbc_snb_driver/commit/27dcd92d4f3b1e2b8594feaf1d78fd190f58567d

**Comment by ArnauPrat** [comment]
As agreed during the meeting, we hardcore this end of simulation time to (2013-01-1). This is the epoch (in milliseconds) I am using to represent this timestamp: 1356998400000

**Comment by alexaverbuch** [comment]
@szarnyasg @ArnauPrat I merged PR locally and then pushed to `dev` branch, so I'm closing here (rather than merging into `master`)

**Pull request closed without merging**
